name: pytest-pull

on:
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install package
        run: uv sync --locked --group dev

      - name: Run pre-commit
        run: uv run pre-commit run --all

      - name: Run pytest
        run: pytest --run-mcmc
